FROM golang:1.25.5-alpine AS builder

WORKDIR /src

RUN apk add --no-cache ca-certificates git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o /out/messagestorage ./cmd/messagestorage

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY --from=builder /out/messagestorage /app/messagestorage

EXPOSE 50052

ENTRYPOINT ["/app/messagestorage"]